-- =====================================================
-- COMPLETE DATABASE SETUP - FIREBASE COMPATIBLE VERSION
-- =====================================================

-- =====================================================
-- 1. PROFILES TABLE (linked to Firebase Auth UIDs)
-- =====================================================
create table if not exists public.profiles (
  id text not null primary key,
  updated_at timestamp with time zone,
  name text,
  role text default 'user' check (role in ('user', 'admin')),
  constraint username_length check (char_length(name) >= 3)
);

-- Disable RLS for profiles table (Firebase compatibility)
alter table public.profiles disable row level security;

-- Drop existing policies if they exist
drop policy if exists "Users can view own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;

-- =====================================================
-- 2. CATEGORIES
-- =====================================================
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- NO RLS for Firebase compatibility
-- alter table public.categories enable row level security;

-- =====================================================
-- 3. PRODUCTS
-- =====================================================
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  price numeric(10,2) not null check (price >= 0),
  category_id bigint references public.categories(id),
  images text[] default '{}',
  stock integer default 0 check (stock >= 0),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- NO RLS for Firebase compatibility
-- alter table public.products enable row level security;

-- =====================================================
-- 4. ORDERS
-- =====================================================
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id text not null references public.profiles(id),
  total numeric(10,2) not null check (total >= 0),
  status text default 'pending' check (status in ('pending','paid','shipped','delivered','cancelled')),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- NO RLS for Firebase compatibility
-- alter table public.orders enable row level security;

-- =====================================================
-- 5. ORDER_ITEMS
-- =====================================================
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity > 0),
  price numeric(10,2) not null check (price >= 0)
);

-- NO RLS for Firebase compatibility
-- alter table public.order_items enable row level security;

-- =====================================================
-- 6. WISHLISTS - NO RLS
-- =====================================================
create table if not exists public.wishlists (
  id bigint generated by default as identity primary key,
  user_id text not null references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamp with time zone default now(),
  unique(user_id, product_id)
);

-- Disable RLS for wishlists table (Firebase compatibility)
alter table public.wishlists disable row level security;

-- Drop existing policies if they exist
drop policy if exists "Users can view own wishlist" on public.wishlists;
drop policy if exists "Users can update own wishlist" on public.wishlists;
drop policy if exists "Users can insert own wishlist" on public.wishlists;

-- Allow all wishlist operations
drop policy if exists "Allow all wishlist operations." on public.wishlists;
create policy "Allow all wishlist operations."
  on public.wishlists for all
  using ( true )
  with check ( true );

-- =====================================================
-- 7. ADDRESSES
-- =====================================================
create table if not exists public.addresses (
  id bigint generated by default as identity primary key,
  user_id text not null references public.profiles(id) on delete cascade,
  label text not null,
  street text not null,
  city text not null,
  state text,
  postal_code text not null,
  country text not null default 'United States',
  is_default boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- NO RLS for Firebase compatibility
-- alter table public.addresses enable row level security;

-- =====================================================
-- 8. REVIEWS
-- =====================================================
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id text not null references public.profiles(id) on delete cascade,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique(product_id, user_id)
);

-- NO RLS for Firebase compatibility
-- alter table public.reviews enable row level security;

-- =====================================================
-- 9. CART_ITEMS (temporary cart for logged-in users) - NO RLS
-- =====================================================
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id text not null references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique(user_id, product_id)
);

-- Allow all cart operations
drop policy if exists "Allow all cart operations." on public.cart_items;
create policy "Allow all cart operations."
  on public.cart_items for all
  using ( true )
  with check ( true );

-- =====================================================
-- 10. USER_PREFERENCES (for theme and other settings)
-- =====================================================
create table if not exists public.user_preferences (
  id bigint generated by default as identity primary key,
  user_id text not null references public.profiles(id) on delete cascade,
  key text not null,
  value text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique(user_id, key)
);

-- NO RLS for Firebase compatibility
-- alter table public.user_preferences enable row level security;

-- =====================================================
-- 11. RECENTLY_VIEWED
-- =====================================================
create table if not exists public.recently_viewed (
  id bigint generated by default as identity primary key,
  user_id text not null references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  viewed_at timestamp with time zone default now(),
  unique(user_id, product_id)
);

-- NO RLS for Firebase compatibility
-- alter table public.recently_viewed enable row level security;

-- =====================================================
-- 12. PAYMENT_METHODS
-- =====================================================
create table if not exists public.payment_methods (
  id bigint generated by default as identity primary key,
  user_id text not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('card', 'paypal', 'bank')),
  provider text not null,
  last_four text,
  expiry_month integer,
  expiry_year integer,
  is_default boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- NO RLS for Firebase compatibility
-- alter table public.payment_methods enable row level security;

-- =====================================================
-- 13. RETURNS
-- =====================================================
create table if not exists public.returns (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  user_id text not null references public.profiles(id) on delete cascade,
  reason text not null,
  status text default 'pending' check (status in ('pending','approved','rejected','completed')),
  refund_amount numeric(10,2),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- NO RLS for Firebase compatibility
-- alter table public.returns enable row level security;

-- =====================================================
-- 15. STORAGE BUCKET FOR PRODUCT IMAGES
-- =====================================================
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

-- Allow public access to product images
drop policy if exists "Public Access" on storage.objects;
create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'product-images' );

-- =====================================================
-- 16. UPDATE PRODUCTS WITH SUPABASE STORAGE IMAGE URLS
-- =====================================================
-- 14. SAMPLE DATA
-- =====================================================
insert into public.categories (name, slug, description) values
('Living Room', 'living-room', 'Sofas, chairs, and coffee tables'),
('Bedroom', 'bedroom', 'Beds, dressers, and nightstands'),
('Dining', 'dining', 'Tables, chairs, and storage')
on conflict (name) do nothing;

insert into public.products (name, slug, description, price, category_id, images, stock) values
('Modern Sofa', 'modern-sofa', 'Comfortable 3-seater sofa', 799.99, 1, array['https://picsum.photos/300/200?random=1'], 10),
('Oak Dining Table', 'oak-dining-table', 'Solid oak dining table for 6', 1299.99, 3, array['https://picsum.photos/300/200?random=2'], 5),
('King Bed Frame', 'king-bed-frame', 'Sturdy wooden king size bed frame', 599.99, 2, array['https://picsum.photos/300/200?random=3'], 8),
('Coffee Table', 'coffee-table', 'Modern glass coffee table', 299.99, 1, array['https://picsum.photos/300/200?random=4'], 15),
('Office Chair', 'office-chair', 'Ergonomic office chair with lumbar support', 199.99, 1, array['https://picsum.photos/300/200?random=5'], 20),
('Bookshelf', 'bookshelf', '5-tier wooden bookshelf', 149.99, 2, array['https://picsum.photos/300/200?random=6'], 12),
('Dining Chair Set', 'dining-chairs', 'Set of 4 modern dining chairs', 399.99, 3, array['https://picsum.photos/300/200?random=7'], 8),
('Nightstand', 'nightstand', 'Wooden nightstand with drawer', 89.99, 2, array['https://picsum.photos/300/200?random=8'], 25)
on conflict (slug) do nothing;
