-- =====================================================
-- CLEANUP: drop existing tables and objects (safe to run multiple times)
-- =====================================================
drop table if exists public.order_items cascade;
drop table if exists public.orders cascade;
drop table if exists public.wishlists cascade;
drop table if exists public.addresses cascade;
drop table if exists public.products cascade;
drop table if exists public.categories cascade;
drop table if exists public.profiles cascade;

drop function if exists public.handle_new_user() cascade;
drop trigger if exists on_auth_user_created on auth.users;

-- =====================================================
-- 1. PROFILES TABLE (linked to Firebase Auth UIDs)
-- =====================================================
create table public.profiles (
  id text not null primary key,
  updated_at timestamp with time zone,
  name text,
  role text default 'user' check (role in ('user', 'admin')),
  constraint username_length check (char_length(name) >= 3)
);

alter table public.profiles enable row level security;

create policy "Users can view own profile."
  on public.profiles for select
  using ( auth.uid()::text = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid()::text = id );

create policy "Users can insert own profile."
  on public.profiles for insert
  with check ( auth.uid()::text = id );

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name)
  values (new.id, new.raw_user_meta_data->>'name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- =====================================================
-- 2. CATEGORIES
-- =====================================================
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.categories enable row level security;

create policy "Categories are viewable by everyone."
  on public.categories for select
  using ( true );

-- =====================================================
-- 3. PRODUCTS
-- =====================================================
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  price numeric(10,2) not null check (price >= 0),
  category_id bigint references public.categories(id),
  images text[] default '{}',
  stock integer default 0 check (stock >= 0),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.products enable row level security;

create policy "Products are viewable by everyone."
  on public.products for select
  using ( true );

-- =====================================================
-- 4. ORDERS
-- =====================================================
create table public.orders (
  id bigint generated by default as identity primary key,
  user_id text not null references public.profiles(id),
  total numeric(10,2) not null check (total >= 0),
  status text default 'pending' check (status in ('pending','paid','shipped','delivered','cancelled')),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.orders enable row level security;

create policy "Users can view own orders."
  on public.orders for select
  using ( auth.uid()::text = user_id );

create policy "Users can insert own orders."
  on public.orders for insert
  with check ( auth.uid()::text = user_id );

-- =====================================================
-- 5. ORDER_ITEMS
-- =====================================================
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity > 0),
  price numeric(10,2) not null check (price >= 0)
);

alter table public.order_items enable row level security;

create policy "Users can view own order items."
  on public.order_items for select
  using ( exists (
    select 1 from public.orders
    where orders.id = order_items.order_id and orders.user_id = auth.uid()::text
  ) );

-- =====================================================
-- 6. WISHLISTS
-- =====================================================
create table public.wishlists (
  id bigint generated by default as identity primary key,
  user_id text not null references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamp with time zone default now(),
  unique(user_id, product_id)
);

alter table public.wishlists enable row level security;

create policy "Users can view own wishlist."
  on public.wishlists for select
  using ( auth.uid()::text = user_id );

create policy "Users can manage own wishlist."
  on public.wishlists for all
  using ( auth.uid()::text = user_id );

-- =====================================================
-- 7. ADDRESSES
-- =====================================================
create table public.addresses (
  id bigint generated by default as identity primary key,
  user_id text not null references public.profiles(id) on delete cascade,
  label text not null,
  street text not null,
  city text not null,
  state text,
  postal_code text not null,
  country text not null default 'United States',
  is_default boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.addresses enable row level security;

create policy "Users can view own addresses."
  on public.addresses for select
  using ( auth.uid()::text = user_id );

create policy "Users can manage own addresses."
  on public.addresses for all
  using ( auth.uid()::text = user_id );

-- =====================================================
-- 8. SAMPLE DATA (optional, remove if not needed)
-- =====================================================
insert into public.categories (name, slug, description) values
('Living Room', 'living-room', 'Sofas, chairs, and coffee tables'),
('Bedroom', 'bedroom', 'Beds, dressers, and nightstands'),
('Dining', 'dining', 'Tables, chairs, and storage');

insert into public.products (name, slug, description, price, category_id, images, stock) values
('Modern Sofa', 'modern-sofa', 'Comfortable 3-seater sofa', 799.99, 1, array['/sofa1.jpg'], 10),
('Oak Dining Table', 'oak-dining-table', 'Solid oak dining table for 6', 1299.99, 3, array['/table1.jpg'], 5),
('King Bed Frame', 'king-bed-frame', 'Sturdy wooden king size bed frame', 599.99, 2, array['/bed1.jpg'], 8);